### ISSUE TITLE
Wires cannot be deleted.

### ISSUE THREAD

**Issue by ouardito** [AOx0/Digital-Logic-Sim-CE#9]
I hover my mouse over a wire, keep spamming Backspace key and cannot delete it.

Any fix ?

**Comment by AOx0** [comment]
Greetings!

I already tracked down the problem to the last commit. Plus, someone sometime set an offset of 0.23 to the Y-coord of the Implementation Holder, which is in charge of the interaction with wires, and caused a weird offset to interact with wires, but now it is just gone.

 I will get this fixed in 1-3 hours with a 0.36.1 release.

Meanwhile, you can connect the wire you want to erase to a temporal chip and then erase it. Like this:

<img width="957" alt="SS1" src="https://user-images.githubusercontent.com/50227494/158079198-f0df30ae-6bdb-4e94-b90e-e3307add1325.png">
<img width="957" alt="SS2" src="https://user-images.githubusercontent.com/50227494/158079197-a1d5f893-eccc-4301-93fa-5ea7f8fdcc85.png">
<img width="957" alt="SS3" src="https://user-images.githubusercontent.com/50227494/158079195-6a0be9a4-02bc-469b-a6f6-71aadc07a068.png">
<img width="957" alt="SS4" src="https://user-images.githubusercontent.com/50227494/158079192-c471b7d3-ce6a-4d13-a7e2-b8f644910880.png">

**Comment by AOx0** [comment]
Ready. Published [v0.36.1 release](https://github.com/AOx0/Digital-Logic-Sim-CE/releases/tag/v0.36.1) with downloadable builds. Let me know if the problem is fixed.

**Comment by ouardito** [comment]
All great, Thanks for the contribution ! <3
